[package]
name = "converter"
version = "0.1.0"
edition = "2021"

[dependencies]
headless_chrome = {git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"]}
pandoc = "0.8.11"
